---
title: Teaching (with) Quarto
subtitle: JSM 2023
listing:
  contents: talks/*/*-index.qmd
  type: grid
  sort:
    - filename
---

Monday, Aug 7\
2:00 PM - 3:50 PM\
[Session \# 1797](https://ww2.aievolution.com/JSMAnnual/index.cfm?do=ev.viewEv&ev=2605) \
Metro Toronto Convention Centre Room: CC-803B 

## Overview

Quarto is an open-source scientific and technical publishing system that unifies and extends the R Markdown ecosystem. This session features five speakers who have been using and teaching R Markdown over the last decade and who have adopted Quarto over the last two years. The speakers will share their experiences teaching Quarto to students in a wide range of courses that span from first-year introductory data science to Master's level statistical computing courses. The talks will also touch on multiple languages and tools as these courses teach R and Python using both RStudio and Jupyter Notebooks. The educators will also discuss building course materials with Quarto, using Quarto for standardizing and organizing student work, as well as for academic authoring broadly. The session will conclude with a discussion on the importance of teaching reproducible computing early and often as well as tips for educators for adopting and teaching new tools and technologies in a constantly evolving landscape.

**Session organizer:** Mine Çetinkaya-Rundel - Duke University + Posit

**Session chair:** Allison Theobold - Cal Poly

**Session speakers:**

-   Mine Çetinkaya-Rundel - Duke University + Posit: Welcome to Quarto: From course notes to journal articles to books
-   Elijah Meyer - Duke University: Teaching Quarto in Intro to Data Science
-   Kelly Bodwin - Cal Poly: Blending R and Python in Quarto documents
-   Colin Rundel - Duke University: Quarto and automation in teaching statistical computing
-   Maria Tackett - Duke University: Using Quarto for Making and Organizing Teaching Materials

## Talks
